apiVersion: v1
kind: ConfigMap
metadata:
  name: reporting-service-config
  labels:
    app: reporting-service
    component: backend
data:
  application.properties: |
    server.port=8083

    spring.datasource.url=jdbc:postgresql://postgres:5432/reportingdb
    spring.datasource.driverClassName=org.postgresql.Driver

    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    spring.application.name=reporting-service

    # Microservice URLs
    service.user.url=http://user-service:8080
    service.task.url=http://task-service:8081

    # Mock service configuration (disable in production)
    use.mock.service=false

    # Actuator Configuration
    management.endpoints.web.exposure.include=health,info,metrics,loggers
    management.endpoint.health.show-details=always
    management.health.db.enabled=true
    management.health.diskspace.enabled=true
