apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  labels:
    app: reporting-service
    component: backend
spec:
  selector:
    app: reporting-service
  ports:
    - port: 8083
      targetPort: 8083
      name: http
  type: ClusterIP
