apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-config
  labels:
    app: task-service
    component: backend
data:
  application.properties: |
    server.port=8081

    spring.datasource.url=jdbc:postgresql://postgres:5432/taskdb
    spring.datasource.driverClassName=org.postgresql.Driver

    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    spring.application.name=task-service

    user.service.url=http://user-service:8080

    # Actuator Configuration
    management.endpoints.web.exposure.include=health,info,metrics,loggers
    management.endpoint.health.show-details=always
    management.health.db.enabled=true
    management.health.diskspace.enabled=true
