apiVersion: v1
kind: Service
metadata:
  name: task-service
  labels:
    app: task-service
    component: backend
spec:
  selector:
    app: task-service
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  type: ClusterIP
