apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  labels:
    app: postgres
    component: database
data:
  init.sql: |
    CREATE DATABASE userdb;
    GRANT ALL PRIVILEGES ON DATABASE userdb TO postgres;

    CREATE DATABASE taskdb;
    GRANT ALL PRIVILEGES ON DATABASE taskdb TO postgres;

    CREATE DATABASE reportingdb;
    GRANT ALL PRIVILEGES ON DATABASE reportingdb TO postgres;
