apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  labels:
    app: postgres
    component: database
data:
  init-scripts.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE userdb;
        GRANT ALL PRIVILEGES ON DATABASE userdb TO postgres;
        
        CREATE DATABASE taskdb;
        GRANT ALL PRIVILEGES ON DATABASE taskdb TO postgres;
        
        CREATE DATABASE reportingdb;
        GRANT ALL PRIVILEGES ON DATABASE reportingdb TO postgres;
    EOSQL
